import React from "react";
import { Image as ImageIcon, MessageSquare, BookOpen, Search, Filter, Share2, Info, Layout } from "lucide-react";

export default function LibraryPage() {
  // Mock data placeholders
  const categories = ["Images", "Prompts", "Captions", "Templates"];
  
  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="rounded-2xl border border-white/5 bg-slate-900/40 p-6 shadow-sm">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
           <div className="flex items-center gap-3">
              <div className="p-2 rounded-xl bg-violet-500/10 text-violet-400">
                 <BookOpen className="h-6 w-6" />
              </div>
              <div>
                 <h2 className="text-xl font-bold text-white tracking-tight">AI Content Library</h2>
                 <p className="text-xs text-slate-400">Manage and reuse your generated AI assets</p>
              </div>
           </div>
           <div className="flex items-center gap-3">
              <div className="relative">
                 <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-slate-500" />
                 <input 
                   type="text" 
                   placeholder="Search library..." 
                   className="pl-9 pr-4 py-2 rounded-xl bg-white/5 border border-white/10 text-xs text-slate-300 outline-none focus:border-violet-500/50 w-48 md:w-64"
                 />
              </div>
              <button className="p-2 rounded-xl bg-white/5 border border-white/10 text-slate-400 hover:text-white transition">
                 <Filter className="h-4 w-4" />
              </button>
           </div>
        </div>

        <div className="mt-6 flex items-start gap-3 p-3 rounded-xl bg-violet-500/5 border border-violet-500/10">
           <Info className="h-5 w-5 text-violet-400 mt-0.5" />
           <div>
              <p className="text-xs font-semibold text-violet-300">Foundation Mode Active</p>
              <p className="text-[10px] text-violet-400/80 leading-relaxed">
                The AI Library is a UI foundation for future centralized asset management. Database persistence for these assets is planned for a later phase.
              </p>
           </div>
        </div>
      </div>

      {/* Grid Layout */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {/* Placeholder: Images */}
        <div className="rounded-2xl border border-white/5 bg-slate-900/40 p-5 shadow-sm hover:border-violet-500/20 transition group">
           <div className="mb-4 flex items-center justify-between">
              <ImageIcon className="h-5 w-5 text-sky-400" />
              <span className="text-[10px] font-bold text-slate-500 uppercase">0 Assets</span>
           </div>
           <h3 className="text-sm font-semibold text-white mb-2">Generated Images</h3>
           <p className="text-[11px] text-slate-500 leading-relaxed mb-4">View and reuse all images generated by AI providers.</p>
           <button className="w-full py-2 rounded-lg bg-white/5 text-[10px] font-bold text-slate-400 uppercase tracking-widest group-hover:bg-violet-500/10 group-hover:text-violet-400 transition">
              Open Gallery
           </button>
        </div>

        {/* Placeholder: Prompts */}
        <div className="rounded-2xl border border-white/5 bg-slate-900/40 p-5 shadow-sm hover:border-violet-500/20 transition group">
           <div className="mb-4 flex items-center justify-between">
              <Layout className="h-5 w-5 text-amber-400" />
              <span className="text-[10px] font-bold text-slate-500 uppercase">0 Saved</span>
           </div>
           <h3 className="text-sm font-semibold text-white mb-2">Saved Prompts</h3>
           <p className="text-[11px] text-slate-500 leading-relaxed mb-4">Store and organize your high-performing prompt briefs.</p>
           <button className="w-full py-2 rounded-lg bg-white/5 text-[10px] font-bold text-slate-400 uppercase tracking-widest group-hover:bg-violet-500/10 group-hover:text-violet-400 transition">
              Manage Prompts
           </button>
        </div>

        {/* Placeholder: Captions */}
        <div className="rounded-2xl border border-white/5 bg-slate-900/40 p-5 shadow-sm hover:border-violet-500/20 transition group">
           <div className="mb-4 flex items-center justify-between">
              <MessageSquare className="h-5 w-5 text-emerald-400" />
              <span className="text-[10px] font-bold text-slate-500 uppercase">0 Drafts</span>
           </div>
           <h3 className="text-sm font-semibold text-white mb-2">Reuse Captions</h3>
           <p className="text-[11px] text-slate-500 leading-relaxed mb-4">A central repository for your best-performing copy.</p>
           <button className="w-full py-2 rounded-lg bg-white/5 text-[10px] font-bold text-slate-400 uppercase tracking-widest group-hover:bg-violet-500/10 group-hover:text-violet-400 transition">
              Browse Copy
           </button>
        </div>

        {/* Placeholder: Templates */}
        <div className="rounded-2xl border border-white/5 bg-slate-900/40 p-5 shadow-sm hover:border-violet-500/20 transition group">
           <div className="mb-4 flex items-center justify-between">
              <Share2 className="h-5 w-5 text-rose-400" />
              <span className="text-[10px] font-bold text-slate-500 uppercase">0 Active</span>
           </div>
           <h3 className="text-sm font-semibold text-white mb-2">Post Templates</h3>
           <p className="text-[11px] text-slate-500 leading-relaxed mb-4">Global templates for consistent multi-page branding.</p>
           <button className="w-full py-2 rounded-lg bg-white/5 text-[10px] font-bold text-slate-400 uppercase tracking-widest group-hover:bg-violet-500/10 group-hover:text-violet-400 transition">
              View Templates
           </button>
        </div>
      </div>

      {/* Empty State Illustration Placeholder */}
      <div className="rounded-2xl border border-dashed border-white/10 p-12 flex flex-col items-center justify-center text-center">
         <div className="h-16 w-16 rounded-full bg-slate-900 flex items-center justify-center mb-4">
            <BookOpen className="h-8 w-8 text-slate-700" />
         </div>
         <h4 className="text-sm font-semibold text-slate-300 mb-2">Library is Empty</h4>
         <p className="text-xs text-slate-500 max-w-xs">Generated content will appear here once the AI Library persistence layer is active.</p>
      </div>
    </div>
  );
}
